In [ ]:
from google.colab import files
import numpy as np
import pandas as pd

data = files.upload()
df=pd.read_csv("heart_attack_prediction_dataset.csv")
df

Saving heart_attack_prediction_dataset.csv to heart_attack_prediction_dataset (2).csv


Patient ID  Age     Sex  Cholesterol  Heart Rate  Diabetes  \
0       BMW7812   67    Male          208          72         0   
1       CZE1114   21    Male          389          98         1   
2       BNI9906   21  Female          324          72         1   
3       JLN3497   84    Male          383          73         1   
4       GFO8847   66    Male          318          93         1   
...         ...  ...     ...          ...         ...       ...   
8758    MSV9918   60    Male          121          61         1   
8759    QSV6764   28  Female          120          73         1   
8760    XKA5925   47    Male          250         105         0   
8761    EPE6801   36    Male          178          60         1   
8762    ZWN9666   25  Female          356          75         1   

      Family History  Smoking  Obesity  Alcohol Consumption  ...  \
0                  0        1        0                    0  ...   
1                  1        1        1                    1  ...   
2                  0        0        0                    0  ...   
3                  1        1        0                    1  ...   
4                  1        1        1                    0  ...   
...              ...      ...      ...                  ...  ...   
8758               1        1        0                    1  ...   
8759               0        0        1                    0  ...   
8760               1        1        1                    1  ...   
8761               0        1        0                    0  ...   
8762               1        0        0                    1  ...   

      Sedentary Hours Per Day  Income        BMI  Triglycerides  \
0                    6.615001  261404  31.251233            286   
1                    4.963459  285768  27.194973            235   
2                    9.463426  235282  28.176571            587   
3                    7.648981  125640  36.464704            378   
4                    1.514821  160555  21.809144            231   
...                       ...     ...        ...            ...   
8758                10.806373  235420  19.655895             67   
8759                 3.833038  217881  23.993866            617   
8760                 2.375214   36998  35.406146            527   
8761                 0.029104  209943  27.294020            114   
8762                 9.005234  247338  32.914151            180   

      Physical Activity Days Per Week  Sleep Hours Per Day         Country  \
0                                   0                    6       Argentina   
1                                   1                    7          Canada   
2                                   4                    4          France   
3                                   3                    4          Canada   
4                                   1                    5        Thailand   
...                               ...                  ...             ...   
8758                                7                    7        Thailand   
8759                                4                    9          Canada   
8760                                4                    4          Brazil   
8761                                2                    8          Brazil   
8762                                7                    4  United Kingdom   

          Continent           Hemisphere  Heart Attack Risk  
0     South America  Southern Hemisphere                  0  
1     North America  Northern Hemisphere                  0  
2            Europe  Northern Hemisphere                  0  
3     North America  Northern Hemisphere                  0  
4              Asia  Northern Hemisphere                  0  
...             ...                  ...                ...  
8758           Asia  Northern Hemisphere                  0  
8759  North America  Northern Hemisphere                  0  
8760  South America  Southern Hemisphere                  1  
8761  South America  

In [ ]:
x = pd.DataFrame(df.iloc[: ,1:6].values) #df.iloc[rowstart:rowend , columnstart:columnend]
y = df.iloc[:, -1:].values #last column (output)
print(x)
print(y)
print('\n')

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, normalize
labelencoder_X = LabelEncoder()
x.loc[:, 1] = labelencoder_X.fit_transform(x.iloc[:, 1]) #gender
#x.iloc[:, 1:3] = normalize(x.iloc[:, 1:3], axis=0).round(4) #cholesterol and heart rate

print(x)

       0       1    2    3  4
0     67    Male  208   72  0
1     21    Male  389   98  1
2     21  Female  324   72  1
3     84    Male  383   73  1
4     66    Male  318   93  1
...   ..     ...  ...  ... ..
8758  60    Male  121   61  1
8759  28  Female  120   73  1
8760  47    Male  250  105  0
8761  36    Male  178   60  1
8762  25  Female  356   75  1

[8763 rows x 5 columns]
[[0]
 [0]
 [0]
 ...
 [1]
 [0]
 [1]]


       0  1    2    3  4
0     67  1  208   72  0
1     21  1  389   98  1
2     21  0  324   72  1
3     84  1  383   73  1
4     66  1  318   93  1
...   .. ..  ...  ... ..
8758  60  1  121   61  1
8759  28  0  120   73  1
8760  47  1  250  105  0
8761  36  1  178   60  1
8762  25  0  356   75  1

[8763 rows x 5 columns]


<ipython-input-2-79a13d0982d4>:10: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  x.loc[:, 1] = labelencoder_X.fit_transform(x.iloc[:, 1]) #gender


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x) #standardize inputs (x)

# Split the data into training (%80) and testing sets (%20)
from sklearn.model_selection import train_test_split
x_train_scaled, x_test_scaled, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights and biases
        self.W1 = np.random.randn(input_size, hidden_size)
        self.b1 = np.zeros((1, hidden_size))
        self.W2 = np.random.randn(hidden_size, output_size)
        self.b2 = np.zeros((1, output_size))

    def get_weights(self):
        return self.W1, self.W2

    def get_biases(self):
        return self.b1, self.b2

    def relu(self, x):
        return np.maximum(0, x)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def forward_propagation(self, X):
        # Input layer to hidden layer
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.relu(self.z1)
        # Hidden layer to output layer
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = self.sigmoid(self.z2)
        return self.a2

    def backward_propagation(self, X, y, learning_rate):
        m = len(X) #number of sample data
        # Compute gradients
        dZ2 = self.a2 - y
        dW2 = (1 / m) * np.dot(self.a1.T, dZ2)
        db2 = (1 / m) * np.sum(dZ2, axis=0, keepdims=True) #keepdims keep the dimension same
        dZ1 = np.dot(dZ2, self.W2.T) * (self.a1 > 0)
        dW1 = (1 / m) * np.dot(X.T, dZ1)
        db1 = (1 / m) * np.sum(dZ1, axis=0, keepdims=True)
        # Update weights and biases
        self.W1 -= learning_rate * dW1
        self.b1 -= learning_rate * db1
        self.W2 -= learning_rate * dW2
        self.b2 -= learning_rate * db2

    def train(self, X, y, learning_rate, num_epochs):
        for epoch in range(num_epochs):
            # Forward propagation
            self.forward_propagation(X)
            # Backward propagation
            self.backward_propagation(X, y, learning_rate)

            loss = np.mean(-y * np.log(self.a2) - (1 - y) * np.log(1 - self.a2))
            if epoch % 10 == 0:
                print(f"Epoch {epoch}, Loss: {loss:.2f}")
            elif epoch == num_epochs -1:
                print(f"Epoch {epoch}, Loss: {loss:.2f}")

    def predict(self, X):
        return np.round(self.forward_propagation(X))

input_size = 5
hidden_size = 5
output_size = 1
learning_rate = 0.01
num_epochs = 100

model = NeuralNetwork(input_size, hidden_size, output_size)

# Train the model
model.train(x_train_scaled, y_train, learning_rate, num_epochs)

# Evaluate the model
predictions = model.predict(x_test_scaled)
accuracy = np.mean(predictions.flatten() == y_test) #accuracy = total of correct predictions / total of predictions
weights = model.get_weights()
biases = model.get_biases()

# Print weights and biases
print("Weights:")
print("Hidden Layer :", weights[0])
print("Output Layer :", weights[1])
print("Biases:")
print("Hidden Layer:", biases[0])
print("Output Layer :", biases[1])

print(f'Test Accuracy: {accuracy:.2f}')

Epoch 0, Loss: 1.63
Epoch 10, Loss: 1.53
Epoch 20, Loss: 1.45
Epoch 30, Loss: 1.37
Epoch 40, Loss: 1.30
Epoch 50, Loss: 1.24
Epoch 60, Loss: 1.18
Epoch 70, Loss: 1.14
Epoch 80, Loss: 1.09
Epoch 90, Loss: 1.05
Epoch 99, Loss: 1.02
Weights:
Hidden Layer : [[-0.98913321  1.06573861  0.4605947  -0.93286716 -0.41720123]
 [ 0.6362852   1.50317006  0.71310758 -0.55539252  0.31282624]
 [ 0.39147451 -0.60602392  1.46244879  0.07580333  0.26737027]
 [ 2.15688486 -0.969098    0.87428016  0.56243995 -0.57628282]
 [-0.9890818   0.2073573   0.21179975 -0.75230502 -0.37546478]]
Output Layer : [[ 0.71582241]
 [-0.55312716]
 [ 0.7798052 ]
 [-1.06130545]
 [-1.68448172]]
Biases:
Hidden Layer: [[-0.14861134  0.00031766 -0.13622561  0.07547557 -0.05481227]]
Output Layer : [[-0.09916266]]
Test Accuracy: 0.55


In [21]:
print('HEART RISK PREDICTION')
print("For this prediction please input numbers\nREFERENCE\nMale= 1  Female=0\nDiabetes\nNo=0 Yes=1\n")
predict_input = input("Please input age Sex Cholesterol Heart_Rate Diabetes in order separated by spaces: ")
predict_list = list(map(float, predict_input.split()))

# Standardize the input data
predict_scaled = scaler.transform([predict_list])

# Predict the risk using the trained model
predicted_risk = model.predict(predict_scaled)
print(f"Heart Risk Detection: {predicted_risk[0][0]:.2f}")
if predicted_risk[0][0] > 0.5:
    print('HIGH RISK')
else:
    print('LOW RISK')

HEART RISK PREDICTION
For this prediction please input numbers
REFERENCE
Male= 1  Female=0
Diabetes
No=0 Yes=1

Please input age Sex Cholesterol Heart_Rate Diabetes in order separated by spaces: 35 0 110 98 0
Heart Risk Detection: 0.00
LOW RISK
